[tool.poetry]
name = "ideal-portfolio"
version = "0.1.0"
description = ""
authors = ["YannFrab <yfrab@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.1"
numpy = "^1.26.4"
pre-commit = "^3.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
